#!/bin/bash

REPOSITORY=braynz-online-platform
BRANCH=$1
DIRREP="../$REPOSITORY"

# Check if repository directory exist
if [ ! -d $DIRREP ]; then
  echo "Checkout repository before deployment"
  exit 1
fi

# Check if branch is supplied
if [ -z $BRANCH ]; then
  echo "First argument must be branch name"
  exit 1
fi

# Checkout branch
git --git-dir="$DIRREP/.git" fetch
git --git-dir="$DIRREP/.git" checkout .
git --git-dir="$DIRREP/.git" checkout $BRANCH
git --git-dir="$DIRREP/.git" checkout .
git --git-dir="$DIRREP/.git" pull

# Denote version
rm -rf .env VERSION
GIT_VERSION=`git --git-dir="$DIRREP/.git" describe --tags --always`
echo $GIT_VERSION > VERSION
cat > .env <<EOL
# Autogenerated config file
# < DO NOT EDIT THIS FILE >
VERSION=${GIT_VERSION}
EOL

systemctl stop docker-compose-app
/usr/local/bin/docker-compose build
systemctl start docker-compose-app
